export const WEDDING_DATE = new Date(1781344800000);
export const GROOM_FIRST_NAME = 'Jace' as const;
export const GROOM_LAST_NAME = 'Warkentien' as const;
export const GROOM_PHONE_NUMBER = '815-289-1606' as const;
export const BRIDE_FIRST_NAME = 'Alyssa' as const;
export const BRIDE_LAST_NAME = 'Ealy' as const;
export const BRIDE_PHONE_NUMBER = '309-373-7482' as const;
export const COUPLE_NAMES = `${BRIDE_FIRST_NAME} and ${GROOM_FIRST_NAME}` as const;
export const WEDDING_LOCATION = 'Quad Cities, IL' as const;
